name: JobTracker

on:
  push:
    branches: [refactor/ui-redesign-v2] # dès qu’on push sur main
  pull_request: # toutes les PR

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # mettre la version utilisée en local

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Build
        run: npm run build
